Fix NameError: undefined subsection_pattern variable
Bug: Line 469 referenced subsection_pattern but that variable was renamed
Error: NameError: name 'subsection_pattern' is not defined

Fix: Track which pattern was used (strict or loose) and use that for re.sub
- Added used_pattern variable
- Set to strict_pattern initially
- Update to loose_pattern if fallback is used
- Use used_pattern in re.sub() call

This fixes the 500 Internal Server Error on file upload.